import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import { TranslationProvider } from '@/context/TranslationContext'
import NavBar from '@/components/common/NavBar'
import FooterSection from '@/components/common/FooterSection'


export const metadata: Metadata = {
  title: 'LAB Home Studio',
  description: 'Generated by create next app',
}


const league = localFont({
  src: [
    {
      path: '../../public/font/LeagueSpartan-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/font/LeagueSpartan-SemiBold.ttf',
      weight: '600',
      style: 'extra-bold',
    },
    {
      path: '../../public/font/LeagueSpartan-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../../public/font/LeagueSpartan-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
        <body  className={league.className}>
          <TranslationProvider>
            <NavBar />
            <div className="mt-24 md:32 lg:mt-8 px-4 md:px-[5rem] 2xl:px-12">
              {children}
              <FooterSection />
            </div>
          </TranslationProvider>
        </body>
    </html>
  )
}

