import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'


export const metadata: Metadata = {
  title: 'LAB Home Studio',
  description: 'Generated by create next app',
}


const league = localFont({
  src: [
    {
      path: '../../public/font/LeagueSpartan-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/font/LeagueSpartan-SemiBold.ttf',
      weight: '600',
      style: 'extra-bold',
    },
    {
      path: '../../public/font/LeagueSpartan-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../../public/font/LeagueSpartan-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={league.className}>
        {children}
      </body>
    </html>
  )
}

